gpu: 0
cache: "cache/fmaps"

sds: True
refine: True
optimize: True
oriented: True

sds_conf:
  train_dir: pretrained
  diff_num_exp: 53
  zoomout: 40

deepfeat_conf:
  fmap: 
    feat: "xyz"
    n_fmap: 30
    C_in: 3
    n_feat: 128 ## Doesn't change
    lambda_: 1e-1
    use_diff: True
    diffusion:
      abs: True
      normalize: False
      time: 1
      batch_sds: 32
      batch_mask: 200

opt:
  n_loop: 300
  soft_p2p: False

loss:
  sds: 1.
  proper: 1.