# misc
misc:
  cuda: True
  device: 0
  checkpoint_interval: 1
  log_interval: 812
  desc: null
  precond: False
  dry_run: False

data:
  root_dir: "data_cache"
  name: DFAUST_fmap_30
  n_fmap: 30
  out: "fmap_exps"
  cond: False
  template_path: "data/template.ply"
  normalize: True
  pairs: False
  abs: True

add_name:
  do: False
  name: "bis"

architecture:
  model: "DiT"
  name_arch: "DiT-S/4"
  input_type: "img"
  cond: False # Conditioning with 3D-CODED

## loss params
#loss:
#  w_gt: False  # if one wants to train as a supervised method, one should set w_gt=True
#  w_ortho: 1   # orthogonal loss for functional map (default: 1)
#  w_Qortho: 0  # orthogonal loss for complex functional map (default: 1)
#  w_bij: 1
#  w_res: 1  # residual loss for functional map (default: 1)
#  w_rank: -0.1
#  w_srnf: 1
#  min_alpha: 1
#  max_alpha: 100
#

hyper_params:
  iterations: 200
  batch_size: 256
  lr: 0.001
  lr_rampup_kimg: 10000 # Learning rate ramp-up duration
  ema_halflife_nshape : 500 # ema half-life of the exponential moving average (EMA) of model weights.
  ema_rampup_ratio : 0.05 # EMA ramp-up coefficient, None = no rampup.
  dropout: 0
  loss_name: 'VPLoss'
  ls : 1 #loss scaling

perfs:
  fp16: False
  workers: 1

resume:
  pkl: null
  transfer: null
  kimg_per_tick: 5
  snapshot_ticks: 50
  state_dump_ticks: 50
